# based on https://github.com/actions/starter-workflows/blob/main/pages/static.yml
name: Publish to GitHub Pages

on:
  push:
    branches: [ rewrite-to-js ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      working-directory: ./web/snuffly
      with:
        node-version: 18
        cache: 'npm'
    - run: npm ci
      working-directory: ./web/snuffly
    - run: npm run build
      working-directory: ./web/snuffly
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: './web/snuffly/build'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
